name: Python CI - Prime Checker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
        - name: Run tests
        run: python -m unittest discover tests

    - name: Build artifact (zip the code)
      run: |
        mkdir -p build_artifacts
        zip -r build_artifacts/prime_checker.zip prime_checker/

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: prime-checker-artifact
        path: build_artifacts/prime_checker.zip
